#
# board/renesas/salvator-x/Makefile
#
# Copyright (C) 2022 MYiR Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	:= ../rcar-common/gen3-spl.o
else
obj-y	:= myc-rzg2l.o ../rcar-common/common.o
endif
